server:
  port: 8080

spring:
  datasource:
    username: guest
    password: 88888888..
    url: jdbc:mysql://www.xd999.online:3306/yz?useUnicode=true&characterEncoding=utf8&allowMultiqueries=true&serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #   数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druidDataSource.stat.mergeSql=true;druidDataSource.stat.slowSqlMillis=500
  mvc:
    view:
      prefix: /webapp/
      suffix: .jsp

mybatis-plus:
  mapper-locations: classpath:mabatis/mapper/*.xml
  # 需要mybatis取别名bean所在的包
  type-aliases-package: org.edu.cdtu.yz.bean,org.edu.cdtu.yz.query


#  # redis配置----------------------------------------------------------------------------------
#  redis:
##    host: 服务器ip地址  # 上线环境
#    host: localhost   # 本地测试
#    password: root
#    database: 0
#    port: 6347
#    timeout: 5000
#  messages:
#    encoding: UTF-8
#
logging:
  file: yz.log
  level:
    root: info
    web: debug

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include:
          - autoconfig
          - beans
          - configprops
          - dump
          - env
          - health
          - info
          - metrics
          - mappings
          - shutdown
          - trace
          - loggers
debug: false
