server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
#  servlet:
#    context-path: /zq_blog  # 设置path

spring:
  datasource:
    username: guest
    password: 88888888..
    url: jdbc:mysql://www.xd999.online:3306/yz?useUnicode=true&characterEncoding=utf8&allowMultiqueries=true&serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis-plus:
  mapper-locations: classpath:mabatis/mapper/*.xml
  type-aliases-package: org.edc.cdtu.yz.bean,org.edc.cdtu.yz.query  #别名


#  # redis配置----------------------------------------------------------------------------------
#  redis:
##    host: 服务器ip地址  # 上线环境
#    host: localhost   # 本地测试
#    password: root
#    database: 0
#    port: 6347
#    timeout: 5000
#  messages:
#    encoding: UTF-8
#
## 打印sql语句
logging:
  file: yz.log
  level:
    root: warn
